# Generated by Django 3.2.13 on 2022-10-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.IntegerField(choices=[(1, '★'), (4, '★★★★'), (5, '★★★★★'), (2, '★★'), (3, '★★★')], default=None),
        ),
    ]
